#!/bin/python
"""
Build text_files/withT/, a copy of text_files/extracted_archive/ in which the in-slab
normal-stress column (17) carries the FULL curvature contribution rather than
its deviatoric part alone.

Background.  Equation 2 of the manuscript contains the curvature term

    (H/2)(dtheta/ds)[(2*Pbar_n - P_subslab - P_wedge) + 2*tau_n]
        = K * H * (sigma_n_bar - P_ext),   P_ext = (P_subslab + P_wedge)/2

i.e. it is built from the TOTAL normal stress sigma_n = tau_n + P_n.  The
extraction writes only the deviatoric part, K*Qn with Qn = H*tau_n_bar
(column 17).  compute_curvature_pressure_term.py measures the missing pressure
part T; this script adds it, so column 17 becomes K*Qn with the redefined
Qn = H*(sigma_n_bar - P_ext).

Every downstream figure script reads withT rather than extracted_archive, so this
script must be run before any of them.  extracted_archive itself, written by
extract_properties.py, is never modified.

The three depths below are the ones the paper uses: the "other" option of the
DP-vs-DP scripts (250, 300, 350 km), which includes the 300 km used by every
other figure. The "normal" option (200, 300, 400 km) is not built.

Rows before t = 11 have no measured T (compute_curvature_pressure_term.py
starts there, matching tmin = 3 in every figure script) and their column 17 is
set to NaN so that any consumer which failed to skip them would fail loudly
rather than silently use an uncorrected value.

Usage:  python3 make_withT.py [depth_m ...]  (default 250e3 300e3 350e3)
"""
import os
import shutil
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, 'text_files', 'extracted_archive')
DST = os.path.join(HERE, 'text_files', 'withT')
TDIR = os.path.join(HERE, 'text_files', 'curvature_pressure_term')

FIRST_TIME = 8
TACTUAL_MIN = 11    # matches tmin = 3 in every figure script
KQN_COL = 17
T_COL = 15          # T_cut in the curvature-pressure output files

SUFFIX = '.shear-dz10.0.ds10.0.prof-dz1.0km.txt'

MODELS = [
    '2D_compositional_subd_lower-res_new_50plates',
    '2D_compositional_subd_lower-res_new_FixedSP_50plates',
    '2D_compositional_subd_lower-res_new_FixedOP_50plates',
    '2D_compositional_subd_lower-res_new_250plates',
    '2D_compositional_subd_lower-res_new_FixedSP_250plates',
    '2D_compositional_subd_lower-res_new_FixedOP_250plates',
    '2D_compositional_subd_lower-res_new_375plates',
    '2D_compositional_subd_lower-res_new_FixedSP_375plates',
    '2D_compositional_subd_lower-res_new_FixedOP_375plates',
    '2D_compositional_subd_lower-res_new2',
    '2D_compositional_subd_FixedSP_lower-res_new2',
    '2D_compositional_subd_FixedOP_lower-res_new',
    '2D_compositional_subd_lower-res_new_1000plates',
    '2D_compositional_subd_lower-res_new_FixedSP_1000plates2',
    '2D_compositional_subd_lower-res_new_FixedOP_1000plates',
]


def main():
    depths = [float(a) for a in sys.argv[1:]] or [250.e3, 300.e3, 350.e3]
    os.makedirs(DST, exist_ok=True)

    n_files = 0
    n_rows = 0
    for depth in depths:
        zkm = '%.1f' % (depth / 1.e3)
        for model in MODELS:
            src = os.path.join(SRC, '%s.z%s%s' % (model, zkm, SUFFIX))
            tf = os.path.join(TDIR, '%s.z%s.txt' % (model, zkm))
            if not os.path.exists(src):
                sys.exit('missing extraction file: %s' % src)
            if not os.path.exists(tf):
                sys.exit('missing curvature-pressure file: %s\n'
                         'run: bash many_curvature-pressure-term.sh %g'
                         % (tf, depth))

            b = np.loadtxt(src)
            tdat = np.atleast_2d(np.loadtxt(tf))

            # NaN every row first, then fill in whatever T actually covers, so
            # a row is either fully corrected or obviously blank. This works
            # whether the curvature-pressure files start at t = 8 or t = 11.
            out = b.copy()
            out[:, KQN_COL] = np.nan
            covered = 0
            for r in tdat:
                irow = int(round(r[0])) - FIRST_TIME
                if 0 <= irow < b.shape[0]:
                    out[irow, KQN_COL] = b[irow, KQN_COL] + r[T_COL]
                    covered += 1

            # every row the figures actually plot must be covered
            need = b.shape[0] - (TACTUAL_MIN - FIRST_TIME)
            if covered < need:
                sys.exit('%s z%s: T covers %d rows, need at least %d'
                         % (model, zkm, covered, need))

            np.savetxt(os.path.join(DST, os.path.basename(src)), out)
            n_files += 1
            n_rows += covered

    # keep a marker so the directory is never mistaken for a real extraction
    with open(os.path.join(DST, 'README.txt'), 'w') as fh:
        fh.write('Generated by make_withT.py. Identical to extracted_archive except\n'
                 'column 17 (K*Qn) carries the full curvature contribution,\n'
                 'K*H*(sigma_n_bar - P_ext), instead of the deviatoric part\n'
                 'alone. Rows before t=11 have column 17 set to NaN.\n'
                 'Do not edit by hand; regenerate from extracted_archive.\n')

    print('wrote %d files (%d corrected rows) to %s' % (n_files, n_rows, DST))


if __name__ == '__main__':
    main()
