#!/bin/python
"""
Build text_files/withT_covered/, a copy of text_files/withT/ in which
timesteps whose slab midplane does not resolve the analysis depth are blanked.

The coverage flag is column 38 of the 300 km-style re-extraction in
text_files/extracted_coverage/ (see many_property-extractions.recheck.sh and the
COLUMNS.txt written beside it).  It is 0 when the analysis depth lies outside
the C_llith = 0.5 midplane contour, or within half a smoothing window of its
end, so that dip and curvature there are edge values rather than local
measurements.

Blanked rows have columns 3, 4, 6, 11 and 17 set to NaN, i.e. everything the
force-balance figures read.  Every plotting routine either skips NaN outright
or scatters a NaN coordinate, which draws nothing, so no downstream change is
needed beyond pointing at this directory.

Only depths with a re-extraction are processed, currently 250, 300 and 350 km.
Depths without one are skipped with a message rather than silently copied, so
nobody mistakes an unfiltered depth for a filtered one.

Usage:  python3 make_withT_covered.py [depth_m ...]
        (default 250e3 300e3 350e3)
"""
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, 'text_files', 'withT')
DST = os.path.join(HERE, 'text_files', 'withT_covered')
COV = os.path.join(HERE, 'text_files', 'extracted_coverage')

SUFFIX = '.shear-dz10.0.ds10.0.prof-dz1.0km.txt'
FIRST_TIME = 8
FLAG_COL = 38
BLANK_COLS = [3, 4, 6, 11, 17]

MODELS = [
    '2D_compositional_subd_lower-res_new_50plates',
    '2D_compositional_subd_lower-res_new_FixedSP_50plates',
    '2D_compositional_subd_lower-res_new_FixedOP_50plates',
    '2D_compositional_subd_lower-res_new_250plates',
    '2D_compositional_subd_lower-res_new_FixedSP_250plates',
    '2D_compositional_subd_lower-res_new_FixedOP_250plates',
    '2D_compositional_subd_lower-res_new_375plates',
    '2D_compositional_subd_lower-res_new_FixedSP_375plates',
    '2D_compositional_subd_lower-res_new_FixedOP_375plates',
    '2D_compositional_subd_lower-res_new2',
    '2D_compositional_subd_FixedSP_lower-res_new2',
    '2D_compositional_subd_FixedOP_lower-res_new',
    '2D_compositional_subd_lower-res_new_1000plates',
    '2D_compositional_subd_lower-res_new_FixedSP_1000plates2',
    '2D_compositional_subd_lower-res_new_FixedOP_1000plates',
]


def main():
    depths = [float(a) for a in sys.argv[1:]] or [250.e3, 300.e3, 350.e3]
    os.makedirs(DST, exist_ok=True)

    n_files = 0
    n_blanked = 0
    for depth in depths:
        zkm = '%.1f' % (depth / 1.e3)
        for model in MODELS:
            name = '%s.z%s%s' % (model, zkm, SUFFIX)
            src = os.path.join(SRC, name)
            cov = os.path.join(COV, name)
            if not os.path.exists(src):
                sys.exit('missing with-T file: %s' % src)
            if not os.path.exists(cov):
                sys.exit('no coverage data for z%s: %s\n'
                         'run: bash many_property-extractions.recheck.sh '
                         'extracted_coverage legacy %ge3' % (zkm, cov, depth / 1.e3))

            b = np.loadtxt(src)
            c = np.loadtxt(cov)
            flag = {int(round(r[0])): r[FLAG_COL] for r in c}

            out = b.copy()
            for irow in range(out.shape[0]):
                t = int(round(out[irow, 0]))
                if flag.get(t, 1.0) == 0.0:
                    out[irow, BLANK_COLS] = np.nan
                    n_blanked += 1

            np.savetxt(os.path.join(DST, name), out)
            n_files += 1

    with open(os.path.join(DST, 'README.txt'), 'w') as fh:
        fh.write('Generated by make_withT_covered.py. Identical to\n'
                 'withT except that timesteps failing the midplane\n'
                 'coverage test (column 38 of extracted_coverage) have columns\n'
                 '3, 4, 6, 11 and 17 set to NaN. Do not edit by hand.\n')

    print('wrote %d files, blanked %d timesteps, to %s'
          % (n_files, n_blanked, DST))


if __name__ == '__main__':
    main()
